### PR TITLE
Update documents

### PR DESCRIPTION
**Pull request by hyrodium**
* Rename `besselroots` to `approx_besselroots`.
  * related: #91
* Update `.github/workflows/ci.yml` to trigger ci with release.
  * With this patch, https://juliaapproximation.github.io/FastGaussQuadrature.jl/stable will be deployed with a new release.
* Move some documents from `README.md` to `doc/src/`.
* Generate [benchmark results](https://juliaapproximation.github.io/FastGaussQuadrature.jl/dev/benchmark/) automatically.

### CODE REVIEW

**Comment by hyrodium** [comment]
Hmm, the doctests seems failing..
I've got no errors in my local pc, so I'll check the ci settings.

**Comment by hyrodium** [comment]
The doctests runs successfully, but the documentation failed.
This is because the `@repl` block in the benchmark needs too much memory to run in GitHub Actions.
```julia
julia> @time gausslegendre( 1000000001 );
 24.441304 seconds (10 allocations: 22.352 GiB, 2.08% gc time)
```
I'll remove the `@repl` block in the document.

**Comment by hyrodium** [comment]
Finished updating documents, and seems ready to merge:tada:

**Comment by hyrodium** [comment]
@dlfivefifty If you have time, could you review this PR? Or, can I merge without reviews?

**Review by dlfivefifty — APPROVED** [review]

**Comment by dlfivefifty** [comment]
Looks good, please bump the version and tag a new release

**Pull request merged**
