### PR TITLE
Optimize polynomial evaluation of coefficients in Gauss-Laguerre

### PR DESCRIPTION
**Pull request by heltonmc**
I noticed that some of the coefficients could be computed significantly faster using Horner's scheme and combining evaluations to reuse as many computations as possible. This significantly reduces the computation time of these evaluations.

```julia
# Master

julia> @benchmark gl_wrapper($1.2, x, 1.2) setup=(x=rand())
BenchmarkTools.Trial: 10000 samples with 10 evaluations.
 Range (min … max):  1.304 μs …  2.617 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     1.317 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.324 μs ± 47.570 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

    ▃ ▇ █ ▆  ▄ ▃              ▁  ▃ ▁                         ▂
  ▇▁█▁█▁█▁█▁▁█▁█▁█▁▇▁▁▇▁█▁▇▁█▁██▁█▁█▁█▁▇▁▁▇▁▇▁▆▁▆▁▁▆▁▆▁▅▁▅▁▄ █
  1.3 μs       Histogram: log(frequency) by time     1.41 μs <

 Memory estimate: 0 bytes, allocs estimate: 0.

# This PR
julia> @benchmark FastGaussQuadrature.gl_bulk($1.2, x, 1.2) setup=(x=rand())
BenchmarkTools.Trial: 10000 samples with 990 evaluations.
 Range (min … max):  44.276 ns … 63.510 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     44.444 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   44.598 ns ±  0.824 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

   ▅█▆▄▃                       ▁                    ▁         ▁
  ██████▆▆▆▅▅▄▄▅▆▅▅▆▆▅▄▆▅▅▆▅▆▅▆██▇▇▅▆▄▄▅▄▄▄▃▁▃▁▃▄▄▆██▅▄▆▅▄▅▁▃ █
  44.3 ns      Histogram: log(frequency) by time      47.7 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```

So the new piece of code is over 25x faster. Of course that is just for that piece of code which is a fraction of the whole routine. For the larger function that is called with 

```julia
# Master
julia> @benchmark FastGaussQuadrature.gausslaguerre_asy_bulk(100, 1.0, 99, x, 11) setup=(x=rand()*0.1)
BenchmarkTools.Trial: 10000 samples with 10 evaluations.
 Range (min … max):  1.142 μs …  2.492 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     1.262 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   1.259 μs ± 40.837 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

                          ▄ ▅▁     ▆█▃▃▂                      
  ▂▂▂▂▂▂▁▂▂▂▂▃▁▃▃▃▃▃▂▁▃▃▄▆█▁██▇▆▅▆▁█████▁▇▅▄▄▅▇▁▆▄▃▃▃▁▃▂▂▃▃▂ ▃
  1.14 μs        Histogram: frequency by time        1.35 μs <

 Memory estimate: 0 bytes, allocs estimate: 0.

# This PR
julia> @benchmark FastGaussQuadrature.gausslaguerre_asy_bulk(100, 1.0, 99, x, 11) setup=(x=rand()*0.1)
BenchmarkTools.Trial: 10000 samples with 636 evaluations.
 Range (min … max):  192.151 ns … 391.313 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     220.715 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   216.940 ns ±  22.124 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  █  ▃ ▁              █▆ ▄▂▁▁           ▃▄ ▅▁ ▁              ▂▁ ▂
  ██▆███▅▄▃▃▅▄▄▃▁▄▃▃▁▃███████▇▅▅▄▅▆▁▃▅▄▁█████▆█▇▇▆▅▃▁▃▄▄▄▁▃▄▁██ █
  192 ns        Histogram: log(frequency) by time        277 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```

So that is roughly 6x faster which is smaller but still very significant. Now calling the larger function...
```julia
# Master
julia> @benchmark FastGaussQuadrature.gausslaguerre_asy(100, x) setup=(x=rand()*0.1)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  162.083 μs … 218.042 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     162.875 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   164.613 μs ±   4.015 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▃▇█▅▃▁▁  ▂▄▂▁   ▁▁ ▁▁▁▁▁▁▂▁▁                                  ▁
  █████████████████████████████▇▇▇▇▆▆▆▆▆▆▄▆▅▇▅▆▅▅▅▆▆▆▅▅▄▅▆▅▆▆▅▆ █
  162 μs        Histogram: log(frequency) by time        182 μs <

 Memory estimate: 3.33 KiB, allocs estimate: 34.

# this PR
julia> @benchmark FastGaussQuadrature.gausslaguerre_asy(100, x) setup=(x=rand()*0.1)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  50.667 μs … 104.958 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     51.209 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   51.948 μs ±   2.506 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▂██▅▃▂    ▂▄▄▄▃▁                                             ▂
  ███████▇▅▇███████▇▇██▇▇▆▆▆▆▆▁▆▆▅▅▆▄▅▅▆▅▃▃▁▃▄▄▄▃▅▁▄▃▁▅▃▃▁▅▅▅▆ █
  50.7 μs       Histogram: log(frequency) by time      65.1 μs <

 Memory estimate: 3.33 KiB, allocs estimate: 34.
```
Which is about ~3.2x faster.

### CODE REVIEW

**Comment by heltonmc** [comment]
I went ahead and removed the instances of `@evalpoly` in the code base and changed to just `evalpoly`. Depending on how the discussion goes in #113 we can change back if needed.

**Comment by heltonmc** [comment]
Sorry for continuing adding more commits (last one). 

I also added faster routines to compute the airy coefficients. These (I don't think) lend them self well to use `evalpoly` but they can be computed using only one cubic root evaluation (the rest are constant propagated). For the airy coefficients since alpha only appears in a single multiply it is faster to just remove that branch (`alph==0`) completely and then we can avoid a lot of code duplication which is not the case for the Bessel coefficients.

```julia
# Master branch of the airy coefficient code block
julia> @benchmark wrapper(1.0, 1.2, x) setup=(x=rand())
BenchmarkTools.Trial: 10000 samples with 916 evaluations.
 Range (min … max):  116.826 ns … 169.379 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     119.825 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   118.818 ns ±   1.865 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▄▇▅                            ▅█▃                   ▁        ▂
  ███▅▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▇█▇▄▅▄▄▅▅▃███▄▁▁▁▁▁▁▁▁▃▁▁▁▁▁▁▁▄██▇▅▅▄▄▅▅ █
  117 ns        Histogram: log(frequency) by time        123 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

# The last commit 
julia> @benchmark gl_airy(1.0, 1.2, x) setup=(x=rand())
BenchmarkTools.Trial: 10000 samples with 998 evaluations.
 Range (min … max):  17.710 ns … 22.605 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     17.763 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   17.773 ns ±  0.147 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

                      ▂▃ ▄▅ ▆█▇▁▇█▇ ▅▄ ▂▁                      
  ▂▂▁▁▁▂▂▂▂▂▃▂▃▄▃▄▅▆▅███▆██▇██████████▇██▇▄▆▅▅▃▄▄▃▄▄▄▃▄▃▃▂▃▂▂ ▄
  17.7 ns         Histogram: frequency by time        17.8 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```

The final benchmarks for this function using a 500 point quadrature look like
```julia
# Master
julia> @benchmark FastGaussQuadrature.gausslaguerre_asy(500, x) setup=(x=rand()*5.0)
BenchmarkTools.Trial: 6834 samples with 1 evaluation.
 Range (min … max):  704.500 μs …  3.611 ms  ┊ GC (min … max): 0.00% … 79.78%
 Time  (median):     725.750 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   729.383 μs ± 41.619 μs  ┊ GC (mean ± σ):  0.06% ±  0.97%

          ▁ ▄▄▇▅█▇▅▅▄▆▃▂                                        
  ▄▇▇█▆▅▆█████████████████▇▆▆▇▅▆▅▆▅▅▅▅▆▄▄▄▄▃▃▂▂▂▂▂▂▂▁▁▁▂▁▁▁▁▁▁ ▄
  704 μs          Histogram: frequency by time          777 μs <

 Memory estimate: 13.66 KiB, allocs estimate: 77.

# This PR
julia> @benchmark FastGaussQuadrature.gausslaguerre_asy(500, x) setup=(x=rand()*5.0)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  163.083 μs …  3.318 ms  ┊ GC (min … max): 0.00% … 94.24%
 Time  (median):     173.500 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   174.703 μs ± 44.615 μs  ┊ GC (mean ± σ):  0.36% ±  1.34%

   ▄▃▁    ▁▄▅▄▅▅▂▃▃▃█▇▅▆▃▁▂▄▃▂▁ ▁                               
  ▅███▆▆▆▅███████████████████████▆▅▅▄▄▃▃▃▃▃▂▂▂▂▂▂▂▂▂▁▂▂▁▂▁▁▁▁▂ ▄
  163 μs          Histogram: frequency by time          196 μs <

 Memory estimate: 13.66 KiB, allocs estimate: 77.
```
So this block of code is now about 4x faster. At this point these coefficients are a fraction of the routine and a lot of the remaining runtime and allocations are coming from the calls to special functions. In the future if you want to consider using `Bessels.jl` for the calls to `besselj`, `airyai`, and `gamma` these allocations and computations could be significantly reduced.

- Michael

**Comment by hyrodium** [comment]
Sorry for the late review. I would approve this PR, but I could not reproduce that much performance improvements in my environment. Could you share your environment?

**On the current master branch**

```julia
julia> using FastGaussQuadrature, BenchmarkTools

julia> @benchmark FastGaussQuadrature.gausslaguerre_asy_bulk(100, 1.0, 99, x, 11) setup=(x=rand()*0.1)
BenchmarkTools.Trial: 10000 samples with 149 evaluations.
 Range (min … max):  690.570 ns …  1.080 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     718.604 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   721.195 ns ± 26.828 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

    ▄   ▇     ▇   █                                             
  ▄▁█▂▇▂█▂▂▃▄▂█▃█▃██▂▃▂▃▂▄▄▃▃▃▆▃▃▂▂▃▂▂▂▂▂▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ ▃
  691 ns          Histogram: frequency by time          807 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark FastGaussQuadrature.gausslaguerre_asy(100, x) setup=(x=rand()*0.1)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  101.373 μs … 161.658 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     104.725 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   105.270 μs ±   3.293 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

         ▃▂▆▂▂▁█                                                 
  ▂▂▂▄▅▅▄████████▅▅▄▄▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▁▁▂▂▂▂▂▂▂▂▂▂▂▂ ▃
  101 μs           Histogram: frequency by time          119 μs <

 Memory estimate: 3.33 KiB, allocs estimate: 34.

julia> @benchmark FastGaussQuadrature.gausslaguerre_asy(500, x) setup=(x=rand()*5.0)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  429.691 μs …  2.434 ms  ┊ GC (min … max): 0.00% … 79.63%
 Time  (median):     445.572 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   446.150 μs ± 30.686 μs  ┊ GC (mean ± σ):  0.09% ±  1.13%

     ▂     ▂▃▁▁▁▂▁▄▃▄▆▇█▄▁▂ ▂ ▁                                 
  ▂▂▃█▆▅▆▄▅████████████████████▆▄▄▄▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂▂▂▂▂▂ ▄
  430 μs          Histogram: frequency by time          480 μs <

 Memory estimate: 13.66 KiB, allocs estimate: 77.
```

**With this PR**

```julia
julia> using FastGaussQuadrature, BenchmarkTools

julia> @benchmark FastGaussQuadrature.gausslaguerre_asy_bulk(100, 1.0, 99, x, 11) setup=(x=rand()*0.1)
BenchmarkTools.Trial: 10000 samples with 155 evaluations.
 Range (min … max):  679.155 ns … 994.852 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     705.594 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   706.604 ns ±  19.795 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

    ▄  ▃  █       ▇▃ ▅  ▇▂                                       
  ▂▁██▁█▄▂█▃▂▂▂▂▂▂██▄██▃██▃▂▂▂▂▂▂▃▆▃▄▅▃▄▆▂▃▂▂▂▂▂▃▂▂▂▃▂▂▃▂▂▂▂▂▁▂ ▃
  679 ns           Histogram: frequency by time          767 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark FastGaussQuadrature.gausslaguerre_asy(100, x) setup=(x=rand()*0.1)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  101.914 μs … 146.979 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     104.603 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   104.954 μs ±   2.177 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

        ▁▂▂ ▁█▆▄▁ ▁▅▆▅▂                                          
  ▄▇▅▅▅▅█████████▇█████▇▆▅▅▅▄▄▄▅▄▄▃▃▃▄▄▃▃▂▃▃▂▂▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂ ▄
  102 μs           Histogram: frequency by time          113 μs <

 Memory estimate: 3.33 KiB, allocs estimate: 34.

julia> @benchmark FastGaussQuadrature.gausslaguerre_asy(500, x) setup=(x=rand()*5.0)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  423.979 μs …  2.550 ms  ┊ GC (min … max): 0.00% … 81.06%
 Time  (median):     441.643 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   441.488 μs ± 30.524 μs  ┊ GC (mean ± σ):  0.09% ±  1.15%

                    ▃▁▂▁ ▁ ▁▁▁▃▂▂▃▃▄▆▅▇██▇▆▅▃▃▂▂▂▁▁▁▁           
  ▁▁▁▂▁▁▁▃█▆▅▄▅▅▆▄▅▇████▇████████████████████████████▇▅▄▄▃▂▂▂▂ ▅
  424 μs          Histogram: frequency by time          454 μs <

 Memory estimate: 13.66 KiB, allocs estimate: 77.
```

**My enviroinment**

```julia
julia> versioninfo()
Julia Version 1.8.0
Commit 5544a0fab76 (2022-08-17 13:38 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 2700X Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver1)
  Threads: 1 on 16 virtual cores
```

**Review by hyrodium — APPROVED** [review]
Sorry for the late review. I would approve this PR, but I could not reproduce that much performance improvements in my environment. Could you share your environment?

**On the current master branch**

```julia
julia> using FastGaussQuadrature, BenchmarkTools

julia> @benchmark FastGaussQuadrature.gausslaguerre_asy_bulk(100, 1.0, 99, x, 11) setup=(x=rand()*0.1)
BenchmarkTools.Trial: 10000 samples with 149 evaluations.
 Range (min … max):  690.570 ns …  1.080 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     718.604 ns              ┊ GC (median):    0.00%
 Time  (mean ± σ):   721.195 ns ± 26.828 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

    ▄   ▇     ▇   █                                             
  ▄▁█▂▇▂█▂▂▃▄▂█▃█▃██▂▃▂▃▂▄▄▃▃▃▆▃▃▂▂▃▂▂▂▂▂▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂ ▃
  691 ns          Histogram: frequency by time          807 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark FastGaussQuadrature.gausslaguerre_asy(100, x) setup=(x=rand()*0.1)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  101.373 μs … 161.658 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     104.725 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   105.270 μs ±   3.293 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

         ▃▂▆▂▂▁█                                                 
  ▂▂▂▄▅▅▄████████▅▅▄▄▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▁▁▂▂▂▂▂▂▂▂▂▂▂▂ ▃
  101 μs           Histogram: frequency by time          119 μs <

 Memory estimate: 3.33 KiB, allocs estimate: 34.

julia> @benchmark FastGaussQuadrature.gausslaguerre_asy(500, x) setup=(x=rand()*5.0)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  429.691 μs …  2.434 ms  ┊ GC (min … max): 0.00% … 79.63%
 Time  (median):     445.572 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   446.150 μs ± 30.686 μs  ┊ GC (mean ± σ):  0.09% ±  1.13%

     ▂     ▂▃▁▁▁▂▁▄▃▄▆▇█▄▁▂ ▂ ▁                                 
  ▂▂▃█▆▅▆▄▅████████████████████▆▄▄▄▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂▂▂▂▂▂▂ ▄
  430 μs          Histogram: frequency by time          480 μs <

 Memory estimate: 13.66 KiB, allocs estimate: 77.
```

**With this PR**

```julia
julia> using FastGaussQuadrature, BenchmarkTools

julia> @benchmark FastGaussQuadrature.gausslaguerre_asy_bulk(100, 1.0, 99, x, 11) setup=(x=rand()*0.1)
BenchmarkTools.Trial: 10000 samples with 155 evaluations.
 Range (min … max):  679.155 ns … 994.852 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     705.594 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   706.604 ns ±  19.795 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

    ▄  ▃  █       ▇▃ ▅  ▇▂                                       
  ▂▁██▁█▄▂█▃▂▂▂▂▂▂██▄██▃██▃▂▂▂▂▂▂▃▆▃▄▅▃▄▆▂▃▂▂▂▂▂▃▂▂▂▃▂▂▃▂▂▂▂▂▁▂ ▃
  679 ns           Histogram: frequency by time          767 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

julia> @benchmark FastGaussQuadrature.gausslaguerre_asy(100, x) setup=(x=rand()*0.1)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  101.914 μs … 146.979 μs  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     104.603 μs               ┊ GC (median):    0.00%
 Time  (mean ± σ):   104.954 μs ±   2.177 μs  ┊ GC (mean ± σ):  0.00% ± 0.00%

        ▁▂▂ ▁█▆▄▁ ▁▅▆▅▂                                          
  ▄▇▅▅▅▅█████████▇█████▇▆▅▅▅▄▄▄▅▄▄▃▃▃▄▄▃▃▂▃▃▂▂▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▂ ▄
  102 μs           Histogram: frequency by time          113 μs <

 Memory estimate: 3.33 KiB, allocs estimate: 34.

julia> @benchmark FastGaussQuadrature.gausslaguerre_asy(500, x) setup=(x=rand()*5.0)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  423.979 μs …  2.550 ms  ┊ GC (min … max): 0.00% … 81.06%
 Time  (median):     441.643 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   441.488 μs ± 30.524 μs  ┊ GC (mean ± σ):  0.09% ±  1.15%

                    ▃▁▂▁ ▁ ▁▁▁▃▂▂▃▃▄▆▅▇██▇▆▅▃▃▂▂▂▁▁▁▁           
  ▁▁▁▂▁▁▁▃█▆▅▄▅▅▆▄▅▇████▇████████████████████████████▇▅▄▄▃▂▂▂▂ ▅
  424 μs          Histogram: frequency by time          454 μs <

 Memory estimate: 13.66 KiB, allocs estimate: 77.
```

**My enviroinment**

```julia
julia> versioninfo()
Julia Version 1.8.0
Commit 5544a0fab76 (2022-08-17 13:38 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 16 × AMD Ryzen 7 2700X Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, znver1)
  Threads: 1 on 16 virtual cores
```

**Comment by heltonmc** [comment]
I am unfortunately away from my desktop (Intel CPU) where I did this right this second but will run later. On my my laptop...

```julia
julia> versioninfo()
Julia Version 1.8.2
Commit 36034abf260 (2022-09-29 15:21 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin21.3.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, apple-m1)
  Threads: 1 on 8 virtual cores

# Master
julia> @benchmark FastGaussQuadrature.gausslaguerre_asy(500, x) setup=(x=rand()*5.0)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  301.875 μs …  8.494 ms  ┊ GC (min … max): 0.00% … 95.74%
 Time  (median):     317.458 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   322.533 μs ± 86.432 μs  ┊ GC (mean ± σ):  0.33% ±  1.30%

    ▁   ▂▂▃▄▃▄▇██▆▄▁                                            
  ▂▆█▇▅██████████████▇▆▅▅▅▅▆█▇▇▆▇▆▆▇▇▇▆▇█▆▆▆▄▄▃▃▂▂▂▂▂▂▂▂▂▁▂▁▁▁ ▄
  302 μs          Histogram: frequency by time          357 μs <

 Memory estimate: 13.66 KiB, allocs estimate: 77.

# This PR
julia> @benchmark FastGaussQuadrature.gausslaguerre_asy(500, x) setup=(x=rand()*5.0)
BenchmarkTools.Trial: 10000 samples with 1 evaluation.
 Range (min … max):  121.208 μs …  3.452 ms  ┊ GC (min … max): 0.00% … 96.08%
 Time  (median):     127.834 μs              ┊ GC (median):    0.00%
 Time  (mean ± σ):   129.131 μs ± 33.610 μs  ┊ GC (mean ± σ):  0.26% ±  0.96%

      ▆▃   ▁▇▆▅▄▇▇▅▄▆█▄           ▁                             
  ▂▇▆▇██▇███████████████▅▃▃▄▄▃▅▆▆██▇▇▆▅▅▃▂▂▂▂▁▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁ ▄
  121 μs          Histogram: frequency by time          146 μs <

 Memory estimate: 13.66 KiB, allocs estimate: 77.
```

So about a 2.5x faster on my Mac. I kinda wish I had an AMD cpu to really see what is going here... it is hard for me to say why the increase is not occurring there. There is a significantly larger improvement on my Intel CPU because of better vectorization of the polynomial evaluations....

**Comment by heltonmc** [comment]
I am a bit perplexed by the `FastGaussQuadrature.gausslaguerre_asy_bulk` benchmark as that should really be much faster. We are essentially reducing the amount of multiplications significantly so those benchmarks should be much different.... on my Mac.

```julia
julia> @benchmark FastGaussQuadrature.gausslaguerre_asy_bulk(100, 1.0, 99, x, 11) setup=(x=rand()*0.1)
BenchmarkTools.Trial: 10000 samples with 195 evaluations.
 Range (min … max):  481.195 ns … 763.887 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     506.836 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   505.045 ns ±  20.273 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▆█▇▃              ▁██▇▄       ▁▁      ▄▆▅▂                 ▂▁ ▂
  ████▆▆▅▃▂▃▄███▆▆▆▅█████▇▇▆▆▄▄▇███▇▆▆▇▆████▇▅▃▄▄▃▃▇▇▆▅▂▃▅▄▃▇██ █
  481 ns        Histogram: log(frequency) by time        560 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.

# this PR
julia> @benchmark FastGaussQuadrature.gausslaguerre_asy_bulk(100, 1.0, 99, x, 11) setup=(x=rand()*0.1)
BenchmarkTools.Trial: 10000 samples with 873 evaluations.
 Range (min … max):  134.164 ns … 282.360 ns  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     158.124 ns               ┊ GC (median):    0.00%
 Time  (mean ± σ):   155.142 ns ±  18.948 ns  ┊ GC (mean ± σ):  0.00% ± 0.00%

  █ ▃                █▅ ▄                ▆▁ ▂                 ▂ ▂
  ███▇█▇▆▆▆▅▄▄▅▃▅▄▄▄▃██████▇▇▇▇▆▅▅▆▆▆▅▅▄▄██▆█▇▅▆▄▄▄▄▄▃▄▄▂▄▄▄▄▃█ █
  134 ns        Histogram: log(frequency) by time        209 ns <

 Memory estimate: 0 bytes, allocs estimate: 0.
```

**Pull request merged**
